"""
Schemas Pydantic pour MassaCorp API
Export tous les schemas pour faciliter les imports
"""
from app.schemas.base import (
    BaseSchema,
    TimestampSchema,
    ResponseBase,
    ErrorDetail,
    ErrorResponse,
    DataResponse,
    PaginationMeta,
    PaginatedResponse,
    HealthResponse,
    success_response,
    error_response,
    paginated_response,
)
from app.schemas.auth import (
    LoginRequest,
    LoginResponse,
    TokenResponse,
    TokenPayload,
    RefreshTokenRequest,
    LogoutRequest,
    PasswordResetRequest,
    PasswordResetConfirm,
    ChangePasswordRequest,
    AuthStatusResponse,
    MFALoginRequest,
    MFARequiredResponse,
    RegisterRequest,
)
from app.schemas.user import (
    UserBase,
    UserCreate,
    UserCreateByAdmin,
    UserUpdate,
    UserUpdateByAdmin,
    UserRead,
    UserReadFull,
    UserInDB,
    UserProfile,
    UserList,
    TenantBase,
    TenantCreate,
    TenantRead,
)
from app.schemas.session import (
    SessionBase,
    SessionRead,
    SessionList,
    SessionTerminateRequest,
    SessionTerminateResponse,
    SessionActivity,
)
from app.schemas.api_key import (
    APIKeyCreate,
    APIKeyRead,
    APIKeyCreated,
    APIKeyList,
    APIKeyRevokeResponse,
)
from app.schemas.gdpr import (
    GDPRExportResponse,
    GDPRDeleteRequest,
    GDPRDeleteResponse,
    GDPRAnonymizeRequest,
    GDPRAnonymizeResponse,
    GDPRInventoryResponse,
    GDPRUserData,
    GDPRSessionData,
    GDPRAuditData,
    GDPRRetentionInfo,
    DataCategory,
    DataProcessor,
    DataSubjectRights,
)
from app.schemas.oauth import (
    OAuthProvider,
    OAuthInitRequest,
    OAuthInitResponse,
    OAuthCallbackRequest,
    OAuthCallbackResponse,
    OAuthCompleteRegistrationRequest,
    OAuthAccountRead,
    OAuthAccountList,
    OAuthUnlinkRequest,
    OAuthProviderInfo,
    OAuthProvidersResponse,
)

__all__ = [
    # Base
    "BaseSchema",
    "TimestampSchema",
    "ResponseBase",
    "ErrorDetail",
    "ErrorResponse",
    "DataResponse",
    "PaginationMeta",
    "PaginatedResponse",
    "HealthResponse",
    "success_response",
    "error_response",
    "paginated_response",
    # Auth
    "LoginRequest",
    "LoginResponse",
    "TokenResponse",
    "TokenPayload",
    "RefreshTokenRequest",
    "LogoutRequest",
    "PasswordResetRequest",
    "PasswordResetConfirm",
    "ChangePasswordRequest",
    "AuthStatusResponse",
    "MFALoginRequest",
    "MFARequiredResponse",
    "RegisterRequest",
    # User
    "UserBase",
    "UserCreate",
    "UserCreateByAdmin",
    "UserUpdate",
    "UserUpdateByAdmin",
    "UserRead",
    "UserReadFull",
    "UserInDB",
    "UserProfile",
    "UserList",
    # Tenant
    "TenantBase",
    "TenantCreate",
    "TenantRead",
    # Session
    "SessionBase",
    "SessionRead",
    "SessionList",
    "SessionTerminateRequest",
    "SessionTerminateResponse",
    "SessionActivity",
    # API Key
    "APIKeyCreate",
    "APIKeyRead",
    "APIKeyCreated",
    "APIKeyList",
    "APIKeyRevokeResponse",
    # GDPR
    "GDPRExportResponse",
    "GDPRDeleteRequest",
    "GDPRDeleteResponse",
    "GDPRAnonymizeRequest",
    "GDPRAnonymizeResponse",
    "GDPRInventoryResponse",
    "GDPRUserData",
    "GDPRSessionData",
    "GDPRAuditData",
    "GDPRRetentionInfo",
    "DataCategory",
    "DataProcessor",
    "DataSubjectRights",
    # OAuth
    "OAuthProvider",
    "OAuthInitRequest",
    "OAuthInitResponse",
    "OAuthCallbackRequest",
    "OAuthCallbackResponse",
    "OAuthCompleteRegistrationRequest",
    "OAuthAccountRead",
    "OAuthAccountList",
    "OAuthUnlinkRequest",
    "OAuthProviderInfo",
    "OAuthProvidersResponse",
]
