"""cleanup_legacy_tables

Revision ID: 9ed31d547bd7
Revises: h8e05d1g3c4f
Create Date: 2025-12-28 21:14:20.272239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ed31d547bd7'
down_revision: Union[str, None] = 'h8e05d1g3c4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop feature_flags_* tables first (they depend on features)
    op.drop_index(op.f('feature_flags_user_idx'), table_name='feature_flags_user')
    op.drop_table('feature_flags_user')
    op.drop_index(op.f('feature_flags_role_idx'), table_name='feature_flags_role')
    op.drop_table('feature_flags_role')
    op.drop_index(op.f('feature_flags_tenant_idx'), table_name='feature_flags_tenant')
    op.drop_table('feature_flags_tenant')
    op.drop_table('feature_flags_global')
    # Now drop features table
    op.drop_table('features')
    # Drop other legacy tables
    op.drop_table('role_hierarchy')
    op.drop_index(op.f('sso_sessions_active_idx'), table_name='sso_sessions', postgresql_where='(revoked_at IS NULL)')
    op.drop_index(op.f('sso_sessions_tenant_idx'), table_name='sso_sessions')
    op.drop_index(op.f('sso_sessions_user_idx'), table_name='sso_sessions')
    op.drop_table('sso_sessions')
    op.drop_index(op.f('identity_providers_enabled_idx'), table_name='identity_providers')
    op.drop_index(op.f('identity_providers_tenant_idx'), table_name='identity_providers')
    op.drop_table('identity_providers')
    op.drop_index(op.f('user_identities_tenant_idx'), table_name='user_identities')
    op.drop_index(op.f('user_identities_user_idx'), table_name='user_identities')
    op.drop_table('user_identities')
    op.drop_index(op.f('api_key_usage_key_idx'), table_name='api_key_usage')
    op.drop_index(op.f('api_key_usage_tenant_idx'), table_name='api_key_usage')
    op.drop_index(op.f('api_key_usage_used_at_idx'), table_name='api_key_usage')
    op.drop_table('api_key_usage')
    op.drop_index(op.f('api_key_roles_key_idx'), table_name='api_key_roles')
    op.drop_index(op.f('api_key_roles_tenant_idx'), table_name='api_key_roles')
    op.drop_table('api_key_roles')
    op.add_column('api_keys', sa.Column('key_prefix', sa.Text(), nullable=False))
    op.add_column('api_keys', sa.Column('created_by_user_id', sa.BigInteger(), nullable=True))
    op.drop_index(op.f('api_keys_active_tenant_idx'), table_name='api_keys', postgresql_where='(revoked_at IS NULL)')
    op.drop_index(op.f('api_keys_expires_at_idx'), table_name='api_keys')
    op.drop_index(op.f('api_keys_key_hash_idx'), table_name='api_keys')
    op.drop_index(op.f('api_keys_last_used_at_idx'), table_name='api_keys')
    op.drop_constraint(op.f('api_keys_tenant_id_name_key'), 'api_keys', type_='unique')
    op.create_index(op.f('ix_api_keys_expires_at'), 'api_keys', ['expires_at'], unique=False)
    op.create_index(op.f('ix_api_keys_tenant_id'), 'api_keys', ['tenant_id'], unique=False)
    op.create_unique_constraint(None, 'api_keys', ['key_hash'])
    op.create_foreign_key(None, 'api_keys', 'users', ['created_by_user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('api_keys', 'scopes')
    op.drop_index(op.f('audit_log_created_at_idx'), table_name='audit_log')
    op.drop_index(op.f('audit_log_event_type_idx'), table_name='audit_log')
    op.drop_index(op.f('audit_log_tenant_idx'), table_name='audit_log')
    op.drop_index(op.f('audit_log_user_idx'), table_name='audit_log')
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_event_type'), 'audit_log', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_log_tenant_id'), 'audit_log', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.drop_index(op.f('login_attempts_attempted_at_idx'), table_name='login_attempts')
    op.drop_index(op.f('login_attempts_identifier_idx'), table_name='login_attempts')
    op.drop_index(op.f('login_attempts_ip_idx'), table_name='login_attempts')
    op.create_index(op.f('ix_login_attempts_attempted_at'), 'login_attempts', ['attempted_at'], unique=False)
    op.create_index(op.f('ix_login_attempts_identifier'), 'login_attempts', ['identifier'], unique=False)
    op.create_index(op.f('ix_login_attempts_ip'), 'login_attempts', ['ip'], unique=False)
    op.drop_index(op.f('mfa_recovery_codes_used_at_idx'), table_name='mfa_recovery_codes')
    op.drop_index(op.f('mfa_recovery_codes_user_idx'), table_name='mfa_recovery_codes')
    op.create_index(op.f('ix_mfa_recovery_codes_used_at'), 'mfa_recovery_codes', ['used_at'], unique=False)
    op.create_index(op.f('ix_mfa_recovery_codes_user_id'), 'mfa_recovery_codes', ['user_id'], unique=False)
    op.drop_index(op.f('mfa_secrets_tenant_idx'), table_name='mfa_secrets')
    op.create_index(op.f('ix_mfa_secrets_tenant_id'), 'mfa_secrets', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_user_created'), table_name='password_reset_tokens')
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.add_column('permissions', sa.Column('code', sa.Text(), nullable=False))
    op.add_column('permissions', sa.Column('resource', sa.Text(), nullable=False))
    op.add_column('permissions', sa.Column('action', sa.Text(), nullable=False))
    op.add_column('permissions', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('permissions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('permissions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('permissions_name_key'), 'permissions', type_='unique')
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_index(op.f('ix_permissions_resource'), 'permissions', ['resource'], unique=False)
    op.create_table_comment(
        'permissions',
        'Permissions atomiques du systeme RBAC',
        existing_comment=None,
        schema=None
    )
    op.alter_column('refresh_tokens', 'session_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('refresh_tokens_active_session_idx'), table_name='refresh_tokens', postgresql_where='(used_at IS NULL)')
    op.drop_index(op.f('refresh_tokens_expires_at_idx'), table_name='refresh_tokens')
    op.drop_index(op.f('refresh_tokens_session_id_idx'), table_name='refresh_tokens')
    op.drop_index(op.f('refresh_tokens_used_at_idx'), table_name='refresh_tokens')
    op.drop_index(op.f('refresh_tokens_used_not_null_idx'), table_name='refresh_tokens', postgresql_where='(used_at IS NOT NULL)')
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_session_id'), 'refresh_tokens', ['session_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_used_at'), 'refresh_tokens', ['used_at'], unique=False)
    op.drop_index(op.f('revoked_tokens_expires_at_idx'), table_name='revoked_tokens')
    op.drop_index(op.f('revoked_tokens_expires_idx'), table_name='revoked_tokens')
    op.create_index(op.f('ix_revoked_tokens_expires_at'), 'revoked_tokens', ['expires_at'], unique=False)
    op.add_column('role_permissions', sa.Column('id', sa.BigInteger(), nullable=False))
    op.add_column('role_permissions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('role_permissions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('role_permissions_permission_idx'), table_name='role_permissions')
    op.drop_index(op.f('role_permissions_role_idx'), table_name='role_permissions')
    op.create_index(op.f('ix_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_unique_constraint('uq_role_permission', 'role_permissions', ['role_id', 'permission_id'])
    op.create_table_comment(
        'role_permissions',
        'Association roles-permissions',
        existing_comment=None,
        schema=None
    )
    op.add_column('roles', sa.Column('code', sa.Text(), nullable=False))
    op.add_column('roles', sa.Column('is_system', sa.Boolean(), nullable=False))
    op.add_column('roles', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('roles', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('roles', 'tenant_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_constraint(op.f('roles_tenant_id_name_key'), 'roles', type_='unique')
    op.drop_index(op.f('roles_tenant_idx'), table_name='roles')
    op.create_index(op.f('ix_roles_code'), 'roles', ['code'], unique=False)
    op.create_index(op.f('ix_roles_tenant_id'), 'roles', ['tenant_id'], unique=False)
    op.create_unique_constraint('uq_role_tenant_code', 'roles', ['tenant_id', 'code'])
    op.create_table_comment(
        'roles',
        'Roles RBAC avec support multi-tenant',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('sessions_active_idx'), table_name='sessions', postgresql_where='(revoked_at IS NULL)')
    op.drop_index(op.f('sessions_revoked_at_idx'), table_name='sessions')
    op.drop_index(op.f('sessions_tenant_active_idx'), table_name='sessions', postgresql_where='(revoked_at IS NULL)')
    op.drop_index(op.f('sessions_tenant_id_idx'), table_name='sessions')
    op.drop_index(op.f('sessions_user_id_idx'), table_name='sessions')
    op.create_index(op.f('ix_sessions_revoked_at'), 'sessions', ['revoked_at'], unique=False)
    op.create_index(op.f('ix_sessions_tenant_id'), 'sessions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.drop_index(op.f('tenants_active_idx'), table_name='tenants', postgresql_where='(is_active = true)')
    op.drop_index(op.f('tenants_slug_idx'), table_name='tenants')
    op.drop_constraint(op.f('tenants_slug_key'), 'tenants', type_='unique')
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.add_column('user_roles', sa.Column('id', sa.BigInteger(), nullable=False))
    op.add_column('user_roles', sa.Column('assigned_by', sa.BigInteger(), nullable=True))
    op.add_column('user_roles', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_roles', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('user_roles', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('user_roles_tenant_idx'), table_name='user_roles')
    op.drop_index(op.f('user_roles_user_idx'), table_name='user_roles')
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_unique_constraint('uq_user_role', 'user_roles', ['user_id', 'role_id'])
    op.drop_constraint(op.f('user_roles_tenant_fk'), 'user_roles', type_='foreignkey')
    op.create_foreign_key(None, 'user_roles', 'users', ['assigned_by'], ['id'], ondelete='SET NULL')
    op.create_table_comment(
        'user_roles',
        'Association utilisateurs-roles',
        existing_comment=None,
        schema=None
    )
    op.drop_column('user_roles', 'assigned_at')
    op.drop_column('user_roles', 'tenant_id')
    op.drop_index(op.f('users_email_lower_idx'), table_name='users')
    op.drop_index(op.f('users_superuser_idx'), table_name='users', postgresql_where='(is_superuser = true)')
    op.drop_index(op.f('users_tenant_active_idx'), table_name='users', postgresql_where='(is_active = true)')
    op.drop_constraint(op.f('users_tenant_id_email_key'), 'users', type_='unique')
    op.drop_index(op.f('users_tenant_idx'), table_name='users')
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table_comment(
        'users',
        'Utilisateurs du systeme avec isolation multi-tenant',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'users',
        existing_comment='Utilisateurs du systeme avec isolation multi-tenant',
        schema=None
    )
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.create_index(op.f('users_tenant_idx'), 'users', ['tenant_id'], unique=False)
    op.create_unique_constraint(op.f('users_tenant_id_email_key'), 'users', ['tenant_id', 'email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('users_tenant_active_idx'), 'users', ['tenant_id', 'is_active'], unique=False, postgresql_where='(is_active = true)')
    op.create_index(op.f('users_superuser_idx'), 'users', ['is_superuser'], unique=False, postgresql_where='(is_superuser = true)')
    op.create_index(op.f('users_email_lower_idx'), 'users', [sa.literal_column('lower(email)')], unique=False)
    op.add_column('user_roles', sa.Column('tenant_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('user_roles', sa.Column('assigned_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_table_comment(
        'user_roles',
        existing_comment='Association utilisateurs-roles',
        schema=None
    )
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.create_foreign_key(op.f('user_roles_tenant_fk'), 'user_roles', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_user_role', 'user_roles', type_='unique')
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.create_index(op.f('user_roles_user_idx'), 'user_roles', ['user_id'], unique=False)
    op.create_index(op.f('user_roles_tenant_idx'), 'user_roles', ['tenant_id'], unique=False)
    op.drop_column('user_roles', 'updated_at')
    op.drop_column('user_roles', 'created_at')
    op.drop_column('user_roles', 'expires_at')
    op.drop_column('user_roles', 'assigned_by')
    op.drop_column('user_roles', 'id')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.create_unique_constraint(op.f('tenants_slug_key'), 'tenants', ['slug'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('tenants_slug_idx'), 'tenants', ['slug'], unique=False)
    op.create_index(op.f('tenants_active_idx'), 'tenants', ['is_active'], unique=False, postgresql_where='(is_active = true)')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_tenant_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_revoked_at'), table_name='sessions')
    op.create_index(op.f('sessions_user_id_idx'), 'sessions', ['user_id'], unique=False)
    op.create_index(op.f('sessions_tenant_id_idx'), 'sessions', ['tenant_id'], unique=False)
    op.create_index(op.f('sessions_tenant_active_idx'), 'sessions', ['tenant_id', 'user_id'], unique=False, postgresql_where='(revoked_at IS NULL)')
    op.create_index(op.f('sessions_revoked_at_idx'), 'sessions', ['revoked_at'], unique=False)
    op.create_index(op.f('sessions_active_idx'), 'sessions', ['id'], unique=False, postgresql_where='(revoked_at IS NULL)')
    op.drop_table_comment(
        'roles',
        existing_comment='Roles RBAC avec support multi-tenant',
        schema=None
    )
    op.drop_constraint('uq_role_tenant_code', 'roles', type_='unique')
    op.drop_index(op.f('ix_roles_tenant_id'), table_name='roles')
    op.drop_index(op.f('ix_roles_code'), table_name='roles')
    op.create_index(op.f('roles_tenant_idx'), 'roles', ['tenant_id'], unique=False)
    op.create_unique_constraint(op.f('roles_tenant_id_name_key'), 'roles', ['tenant_id', 'name'], postgresql_nulls_not_distinct=False)
    op.alter_column('roles', 'tenant_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('roles', 'updated_at')
    op.drop_column('roles', 'is_active')
    op.drop_column('roles', 'is_system')
    op.drop_column('roles', 'code')
    op.drop_table_comment(
        'role_permissions',
        existing_comment='Association roles-permissions',
        schema=None
    )
    op.drop_constraint('uq_role_permission', 'role_permissions', type_='unique')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_permission_id'), table_name='role_permissions')
    op.create_index(op.f('role_permissions_role_idx'), 'role_permissions', ['role_id'], unique=False)
    op.create_index(op.f('role_permissions_permission_idx'), 'role_permissions', ['permission_id'], unique=False)
    op.drop_column('role_permissions', 'updated_at')
    op.drop_column('role_permissions', 'created_at')
    op.drop_column('role_permissions', 'id')
    op.drop_index(op.f('ix_revoked_tokens_expires_at'), table_name='revoked_tokens')
    op.create_index(op.f('revoked_tokens_expires_idx'), 'revoked_tokens', [sa.literal_column('expires_at DESC')], unique=False)
    op.create_index(op.f('revoked_tokens_expires_at_idx'), 'revoked_tokens', ['expires_at'], unique=False)
    op.drop_index(op.f('ix_refresh_tokens_used_at'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_session_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.create_index(op.f('refresh_tokens_used_not_null_idx'), 'refresh_tokens', ['jti'], unique=False, postgresql_where='(used_at IS NOT NULL)')
    op.create_index(op.f('refresh_tokens_used_at_idx'), 'refresh_tokens', ['used_at'], unique=False)
    op.create_index(op.f('refresh_tokens_session_id_idx'), 'refresh_tokens', ['session_id'], unique=False)
    op.create_index(op.f('refresh_tokens_expires_at_idx'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('refresh_tokens_active_session_idx'), 'refresh_tokens', ['session_id', 'expires_at'], unique=False, postgresql_where='(used_at IS NULL)')
    op.alter_column('refresh_tokens', 'session_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_table_comment(
        'permissions',
        existing_comment='Permissions atomiques du systeme RBAC',
        schema=None
    )
    op.drop_index(op.f('ix_permissions_resource'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.create_unique_constraint(op.f('permissions_name_key'), 'permissions', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('permissions', 'updated_at')
    op.drop_column('permissions', 'created_at')
    op.drop_column('permissions', 'is_active')
    op.drop_column('permissions', 'action')
    op.drop_column('permissions', 'resource')
    op.drop_column('permissions', 'code')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.create_index(op.f('ix_password_reset_tokens_user_created'), 'password_reset_tokens', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=False)
    op.drop_index(op.f('ix_mfa_secrets_tenant_id'), table_name='mfa_secrets')
    op.create_index(op.f('mfa_secrets_tenant_idx'), 'mfa_secrets', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_mfa_recovery_codes_user_id'), table_name='mfa_recovery_codes')
    op.drop_index(op.f('ix_mfa_recovery_codes_used_at'), table_name='mfa_recovery_codes')
    op.create_index(op.f('mfa_recovery_codes_user_idx'), 'mfa_recovery_codes', ['user_id'], unique=False)
    op.create_index(op.f('mfa_recovery_codes_used_at_idx'), 'mfa_recovery_codes', ['used_at'], unique=False)
    op.drop_index(op.f('ix_login_attempts_ip'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_identifier'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_attempted_at'), table_name='login_attempts')
    op.create_index(op.f('login_attempts_ip_idx'), 'login_attempts', ['ip'], unique=False)
    op.create_index(op.f('login_attempts_identifier_idx'), 'login_attempts', ['identifier'], unique=False)
    op.create_index(op.f('login_attempts_attempted_at_idx'), 'login_attempts', ['attempted_at'], unique=False)
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_tenant_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_event_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.create_index(op.f('audit_log_user_idx'), 'audit_log', ['user_id'], unique=False)
    op.create_index(op.f('audit_log_tenant_idx'), 'audit_log', ['tenant_id'], unique=False)
    op.create_index(op.f('audit_log_event_type_idx'), 'audit_log', ['event_type'], unique=False)
    op.create_index(op.f('audit_log_created_at_idx'), 'audit_log', ['created_at'], unique=False)
    op.add_column('api_keys', sa.Column('scopes', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'api_keys', type_='foreignkey')
    op.drop_constraint(None, 'api_keys', type_='unique')
    op.drop_index(op.f('ix_api_keys_tenant_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_expires_at'), table_name='api_keys')
    op.create_unique_constraint(op.f('api_keys_tenant_id_name_key'), 'api_keys', ['tenant_id', 'name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('api_keys_last_used_at_idx'), 'api_keys', ['last_used_at'], unique=False)
    op.create_index(op.f('api_keys_key_hash_idx'), 'api_keys', ['key_hash'], unique=False)
    op.create_index(op.f('api_keys_expires_at_idx'), 'api_keys', ['expires_at'], unique=False)
    op.create_index(op.f('api_keys_active_tenant_idx'), 'api_keys', ['tenant_id'], unique=False, postgresql_where='(revoked_at IS NULL)')
    op.drop_column('api_keys', 'created_by_user_id')
    op.drop_column('api_keys', 'key_prefix')
    op.create_table('feature_flags_tenant',
    sa.Column('feature_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], name=op.f('feature_flags_tenant_feature_fk'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('feature_flags_tenant_tenant_fk'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feature_id', 'tenant_id', name=op.f('feature_flags_tenant_pkey'))
    )
    op.create_index(op.f('feature_flags_tenant_idx'), 'feature_flags_tenant', ['tenant_id'], unique=False)
    op.create_table('feature_flags_global',
    sa.Column('feature_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], name=op.f('feature_flags_global_feature_fk'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feature_id', name=op.f('feature_flags_global_pkey'))
    )
    op.create_table('api_key_roles',
    sa.Column('api_key_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], name=op.f('api_key_roles_key_fk'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('api_key_roles_role_fk'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('api_key_roles_tenant_fk'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('api_key_id', 'role_id', name=op.f('api_key_roles_pkey'))
    )
    op.create_index(op.f('api_key_roles_tenant_idx'), 'api_key_roles', ['tenant_id'], unique=False)
    op.create_index(op.f('api_key_roles_key_idx'), 'api_key_roles', ['api_key_id'], unique=False)
    op.create_table('api_key_usage',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('api_key_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ip', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('endpoint', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('method', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('used_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], name=op.f('api_key_usage_fk'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('api_key_usage_tenant_fk'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('api_key_usage_pkey'))
    )
    op.create_index(op.f('api_key_usage_used_at_idx'), 'api_key_usage', ['used_at'], unique=False)
    op.create_index(op.f('api_key_usage_tenant_idx'), 'api_key_usage', ['tenant_id'], unique=False)
    op.create_index(op.f('api_key_usage_key_idx'), 'api_key_usage', ['api_key_id'], unique=False)
    op.create_table('user_identities',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('provider_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('external_subject', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('user_identities_tenant_fk'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_identities_user_fk'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_identities_pkey')),
    sa.UniqueConstraint('tenant_id', 'provider_name', 'external_subject', name=op.f('user_identities_tenant_id_provider_name_external_subject_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('user_identities_user_idx'), 'user_identities', ['user_id'], unique=False)
    op.create_index(op.f('user_identities_tenant_idx'), 'user_identities', ['tenant_id'], unique=False)
    op.create_table('identity_providers',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('provider_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('provider_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('client_secret', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('issuer_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('saml_entity_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('saml_metadata', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('identity_providers_tenant_fk'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('identity_providers_pkey')),
    sa.UniqueConstraint('tenant_id', 'provider_name', name=op.f('identity_providers_tenant_id_provider_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('identity_providers_tenant_idx'), 'identity_providers', ['tenant_id'], unique=False)
    op.create_index(op.f('identity_providers_enabled_idx'), 'identity_providers', ['enabled'], unique=False)
    op.create_table('feature_flags_role',
    sa.Column('feature_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], name=op.f('feature_flags_role_feature_fk'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feature_id', 'role_id', name=op.f('feature_flags_role_pkey'))
    )
    op.create_index(op.f('feature_flags_role_idx'), 'feature_flags_role', ['role_id'], unique=False)
    op.create_table('sso_sessions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('provider_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('external_session_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('sso_sessions_tenant_fk'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('sso_sessions_user_fk'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('sso_sessions_pkey'))
    )
    op.create_index(op.f('sso_sessions_user_idx'), 'sso_sessions', ['user_id'], unique=False)
    op.create_index(op.f('sso_sessions_tenant_idx'), 'sso_sessions', ['tenant_id'], unique=False)
    op.create_index(op.f('sso_sessions_active_idx'), 'sso_sessions', ['id'], unique=False, postgresql_where='(revoked_at IS NULL)')
    op.create_table('features',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('features_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='features_pkey'),
    sa.UniqueConstraint('key', name='features_key_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('feature_flags_user',
    sa.Column('feature_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], name=op.f('feature_flags_user_feature_fk'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('feature_flags_user_user_fk'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feature_id', 'user_id', name=op.f('feature_flags_user_pkey'))
    )
    op.create_index(op.f('feature_flags_user_idx'), 'feature_flags_user', ['user_id'], unique=False)
    op.create_table('role_hierarchy',
    sa.Column('parent_role_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('child_role_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['child_role_id'], ['roles.id'], name=op.f('role_hierarchy_child_fk'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_role_id'], ['roles.id'], name=op.f('role_hierarchy_parent_fk'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parent_role_id', 'child_role_id', name=op.f('role_hierarchy_pkey'))
    )
    # ### end Alembic commands ###
